#!/bin/bash
data=(`find /var/log/ -name '*.log'`);
for log in "${data[@]}"; do
	echo "$log clear"
	echo -n > $log
done
data=(`find /var/log/ -name '*.err'`);
for log in "${data[@]}"; do
	echo "$log clear"
	echo -n > $log
done
data=(`find /var/log/ -name 'mail.*'`);
for log in "${data[@]}"; do
	echo "$log clear"
	echo -n > $log
done
echo -n > /var/log/syslog
echo -n > /var/log/btmp
echo -n > /var/log/messages
echo -n > /var/log/debug
bcc=`date`
echo ""
echo "Successfully clean log at $bcc"
sleep 0.5
clear
echo ""
