#!/bin/bash
export domain1=$(cat /etc/xray/domain)
REPOKU="https://www.vmessh.cloud"
REPOSC="https://iam.scvpn.cloud"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
export NC="\e[0m"
export YELLOW='\033[0;33m';
export RED="\033[0;31m"
export COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
export COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ "$date_list" > "$useexp" ]]; then
        systemctl stop nginx
        systemctl stop kyt
        systemctl stop xray
        systemctl stop ws-stunnel
        dilarang
        exit 1
    else
        echo -ne
    fi
}
checking_sc
mkdir -p /etc/botexp/
clear
echo -e "$COLOR1
 ╔═════════════════════════════════════════════════╗
 ║${WH}     This Feature Can Only Be Used According     ${COLOR1}║
 ║${WH}        To VPS Data With This Autoscript         ${COLOR1}║
 ║${WH}                                                 ${COLOR1}║
 ║${WH}       Please Insert VPS Data Backup Link        ${COLOR1}║
 ║${WH}              To Restore The Data                ${COLOR1}║
 ╚═════════════════════════════════════════════════╝
${NC}"
read -rp " Link File: " -e url
cd
echo
echo -e " [ ${COLOR1}INFO${NC} ] Downloading . . ."
mkdir -p /root/backup
wget -O backup.zip "$url" &> /dev/null
unzip backup.zip  &> /dev/null
rm -f backup.zip
sleep 1
cd /root/backup
echo -e " [ ${COLOR1}INFO${NC} ] Restoring . . ."
sleep 2
cp -r passwd /etc/ &> /dev/null
cp -r group /etc/ &> /dev/null
cp -r shadow /etc/ &> /dev/null
cp -r xray /etc/xray/config.json &> /dev/null
cp -r ssh /etc/xray/ssh &> /dev/null
cp -r domain /etc/xray/domain &> /dev/null
cp -r domain /etc/v2ray/domain &> /dev/null
cp -r idchat /usr/bin/idchat &> /dev/null
cp -r token /usr/bin/token &> /dev/null
cp -r id /etc/per/id &> /dev/null
cp -r token2 /etc/per/token &> /dev/null
cp -r loginid /etc/perlogin/id &> /dev/null
cp -r logintoken /etc/perlogin/token &> /dev/null
cp -r expid /etc/botexp/id &> /dev/null
cp -r exptoken /etc/botexp/token &> /dev/null
cp -r public_html /home/vps/ &> /dev/null
cp -r gshadow /etc/ &> /dev/null
cp -r sshx /etc/xray/ &> /dev/null
cp -r vmess /etc/ &> /dev/null
cp -r vless /etc/ &> /dev/null
cp -r trojan /etc/ &> /dev/null
cp -r issue /etc/issue.net &> /dev/null
domain2=$(cat /etc/xray/domain)
echo "IP=$domain2" > /var/lib/ipvps.conf
echo -e " [ ${COLOR1}INFO${NC} ] VPS Data Restore Complete !"
sleep 1
echo -e " [ ${COLOR1}INFO${NC} ] Restart All Service . . ."
systemctl restart xray
systemctl restart nginx
IP=$(curl -sS ipinfo.io/ip)
TD=$(date +"%d-%m-%Y | %H:%M %Z")
domain=$(cat /etc/xray/domain)
KEY=$(cat /usr/bin/token)
CHATID=$(cat /usr/bin/idchat)
TIMES="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
TEKS="
━━━━━━━━━━━━━━━━━━━━━━━
  <b>☘ RESTORE VPS COMPLETED ☘</b>
━━━━━━━━━━━━━━━━━━━━━━━
<b>● IP :</b> <code>$IP</code>
<b>● Old Host :</b> <code>$domain1</code>
<b>● New Host :</b> <code>$domain</code>
<b>● ISP :</b> <code>$ISP</code>
<b>● CITY :</b> <code>$CITY</code>
━━━━━━━━━━━━━━━━━━━━━━━
       <code>$TD</code>
━━━━━━━━━━━━━━━━━━━━━━━
» @alawivpn
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEKS&parse_mode=html" $URL >/dev/null

cd
rm -rf /root/backup
echo -e " [ ${COLOR1}INFO${NC} ] Done!"
sleep 1
echo
read -n 1 -s -r -p " Press any key to back on menu"
menu
